// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import NosotrosMediaOverlay from '@/components/sections/about/NosotrosMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function NosotrosSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <NosotrosMediaOverlay
          tag="Quiénes Somos"
          title="Partner Integral en Transformación Digital"
          description="Renexa no solo implementa herramientas; rediseñamos el futuro de tu empresa. Combinamos diseño web de alta conversión con tecnología de IA avanzada para que tú te enfoques en lo que más importa: hacer crecer tu negocio."
          imageSrc="http://img.b2bpic.net/free-photo/group-graphic-designers-working-computer_1170-2926.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
