// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "bento" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function BentoSection(): React.JSX.Element {
  return (
    <div id="bento" data-section="bento">
        <SectionErrorBoundary name="bento">
              <FeaturesRevealCardsBento
        tag="IA Especializada"
        title="9 Pilares para la Transformación Inteligente"
        description="Implementamos soluciones específicas adaptadas a tus objetivos operativos y comerciales."
        items={[{"imageSrc":"http://img.b2bpic.net/free-photo/3d-render-science-background-with-connecting-lines-dots_1048-13023.jpg","description":"Flujos de trabajo autónomos para back-office.","href":"#contact","title":"Automatización de Tareas"},{"href":"#contact","title":"Pronóstico de Ventas","imageSrc":"http://img.b2bpic.net/free-photo/3d-abstract-particle-background_1048-11982.jpg","description":"Inteligencia de datos para predecir cierres y tendencias."},{"description":"Atención personalizada 24/7 con IA avanzada.","title":"Asistentes de IA","href":"#contact","imageSrc":"http://img.b2bpic.net/free-photo/portrait-happy-system-administrators-data-center-using-devices_482257-120660.jpg"},{"title":"Precios Dinámicos","href":"#contact","description":"Ajuste inteligente de precios en tiempo real según demanda.","imageSrc":"http://img.b2bpic.net/free-photo/business-leader-trader-searching-new-investment-solution_482257-116895.jpg"},{"imageSrc":"http://img.b2bpic.net/free-photo/cheerful-person-relaxing-apartment-enjoying-film-laptop_482257-116359.jpg","description":"Conexión fluida de sistemas y plataformas empresariales.","href":"#contact","title":"Integraciones Inteligentes"},{"description":"Supervisión constante de rendimiento comercial y procesos.","href":"#contact","imageSrc":"http://img.b2bpic.net/free-photo/male-worker-holding-smartphone-with-horizontal-green-screen-business-office-young-adult-working-with-blank-chroma-key-isolated-template-with-mockup-background-mobile-phone-display_482257-40952.jpg","title":"Monitoreo en Tiempo Real"},{"href":"#contact","imageSrc":"http://img.b2bpic.net/free-photo/3d-rendering-robot-hand-holding-metal-3d-mechanical-gear_181624-58873.jpg","title":"Generación de Contenido","description":"Creación automática de contenido estratégico con IA."}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
