/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";

const primaryButton = {
  text: "Solicitar demostración",
  href: "#contact"
};
const secondaryButton = {
  text: "Hablar con consultor",
  href: "#contact"
};

const ContactInline = () => {
  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="slide-up">
          <div className="flex flex-col items-center gap-8 md:gap-10 py-20 px-8 rounded card">
            <div className="flex flex-col items-center gap-2">
              <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                <p>{"Contacto"}</p>
              </div>

              <TextAnimation
                text={"¿Listo para escalar tu empresa?"}
                variant={"slide-up"}
                gradientText={true}
                tag="h2"
                className="md:max-w-8/10 text-5xl 2xl:text-6xl leading-[1.15] font-semibold text-center text-balance"
              />

              <div className="flex flex-col sm:flex-row items-center gap-6 mt-4 mb-2 text-foreground">
                <a href="mailto:hola@renexa.es" className="flex items-center gap-2 hover:text-primary-cta transition-colors text-base font-medium">
                  <span>hola@renexa.es</span>
                </a>
                <a href="tel:+34604250250" className="flex items-center gap-2 hover:text-primary-cta transition-colors text-base font-medium">
                  <span>604 250 250</span>
                </a>
              </div>

              <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
                <Button text={primaryButton.text} href="mailto:hola@renexa.es" variant="primary" />
                <Button text={secondaryButton.text} href="tel:+34604250250" variant="secondary" animationDelay={0.1} />
              </div>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
