/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { useState } from "react";
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import { Mail, Phone, Send, Check } from "lucide-react";

const ContactInline = () => {
  const [formData, setFormData] = useState({
    nombre: "",
    email: "",
    telefono: "",
    empresa: "",
    mensaje: ""
  });
  const [submitted, setSubmitted] = useState(false);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const subject = encodeURIComponent(`Nueva solicitud de información de ${formData.nombre}`);
    const body = encodeURIComponent(
      `Nombre: ${formData.nombre}\n` +
      `Email: ${formData.email}\n` +
      `Teléfono: ${formData.telefono}\n` +
      `Empresa: ${formData.empresa}\n\n` +
      `Mensaje:\n${formData.mensaje}`
    );
    window.location.href = `mailto:hola@renexa.es?subject=${subject}&body=${body}`;
    setSubmitted(true);
  };

  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="slide-up">
          <div className="flex flex-col items-center gap-8 md:gap-10 py-16 px-6 md:px-12 rounded card max-w-4xl mx-auto">
            <div className="flex flex-col items-center gap-2 text-center max-w-2xl">
              <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                <p className="text-foreground">Formulario de Solicitud</p>
              </div>

              <TextAnimation
                text="¿Listo para escalar tu empresa?"
                variant="slide-up"
                gradientText={true}
                tag="h2"
                className="text-4xl md:text-5xl font-semibold text-center leading-tight text-balance"
              />

              <p className="text-accent text-base md:text-lg mt-2">
                Rellena tus datos y nuestro equipo se pondrá en contacto contigo a la brevedad.
              </p>
            </div>

            {submitted ? (
              <div className="w-full max-w-xl p-8 rounded card flex flex-col items-center text-center gap-4">
                <div className="w-12 h-12 rounded-full bg-primary-cta/20 text-primary-cta flex items-center justify-center">
                  <Check className="w-6 h-6" />
                </div>
                <h3 className="text-2xl font-bold text-foreground">¡Solicitud enviada!</h3>
                <p className="text-accent text-sm md:text-base">
                  Se ha preparado el mensaje para ser enviado a <strong>hola@renexa.es</strong>. Si no se abrió automáticamente tu cliente de correo, puedes escribirnos directamente.
                </p>
                <button
                  onClick={() => setSubmitted(false)}
                  className="mt-2 text-sm text-primary-cta hover:underline font-medium cursor-pointer"
                >
                  Enviar otra solicitud
                </button>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="w-full max-w-xl flex flex-col gap-5">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="flex flex-col gap-2">
                    <label htmlFor="nombre" className="text-sm font-medium text-foreground">
                      Nombre completo <span className="text-primary-cta">*</span>
                    </label>
                    <input
                      type="text"
                      id="nombre"
                      name="nombre"
                      required
                      placeholder="Tu nombre"
                      value={formData.nombre}
                      onChange={handleChange}
                      className="w-full px-4 py-3 rounded bg-background border border-accent/30 text-foreground placeholder:text-accent/60 focus:outline-none focus:border-primary-cta transition-colors text-sm"
                    />
                  </div>

                  <div className="flex flex-col gap-2">
                    <label htmlFor="email" className="text-sm font-medium text-foreground">
                      Correo electrónico <span className="text-primary-cta">*</span>
                    </label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      required
                      placeholder="tu@email.com"
                      value={formData.email}
                      onChange={handleChange}
                      className="w-full px-4 py-3 rounded bg-background border border-accent/30 text-foreground placeholder:text-accent/60 focus:outline-none focus:border-primary-cta transition-colors text-sm"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="flex flex-col gap-2">
                    <label htmlFor="telefono" className="text-sm font-medium text-foreground">
                      Teléfono
                    </label>
                    <input
                      type="tel"
                      id="telefono"
                      name="telefono"
                      placeholder="+34 600 000 000"
                      value={formData.telefono}
                      onChange={handleChange}
                      className="w-full px-4 py-3 rounded bg-background border border-accent/30 text-foreground placeholder:text-accent/60 focus:outline-none focus:border-primary-cta transition-colors text-sm"
                    />
                  </div>

                  <div className="flex flex-col gap-2">
                    <label htmlFor="empresa" className="text-sm font-medium text-foreground">
                      Empresa / Organización
                    </label>
                    <input
                      type="text"
                      id="empresa"
                      name="empresa"
                      placeholder="Nombre de tu empresa"
                      value={formData.empresa}
                      onChange={handleChange}
                      className="w-full px-4 py-3 rounded bg-background border border-accent/30 text-foreground placeholder:text-accent/60 focus:outline-none focus:border-primary-cta transition-colors text-sm"
                    />
                  </div>
                </div>

                <div className="flex flex-col gap-2">
                  <label htmlFor="mensaje" className="text-sm font-medium text-foreground">
                    Detalles de la solicitud <span className="text-primary-cta">*</span>
                  </label>
                  <textarea
                    id="mensaje"
                    name="mensaje"
                    required
                    rows={4}
                    placeholder="Cuéntanos brevemente qué necesitas o en qué podemos ayudarte..."
                    value={formData.mensaje}
                    onChange={handleChange}
                    className="w-full px-4 py-3 rounded bg-background border border-accent/30 text-foreground placeholder:text-accent/60 focus:outline-none focus:border-primary-cta transition-colors text-sm resize-none"
                  />
                </div>

                <button
                  type="submit"
                  className="primary-button flex items-center justify-center gap-2 py-3.5 px-6 rounded font-semibold transition-all hover:opacity-95 cursor-pointer mt-2"
                >
                  <Send className="w-4 h-4" />
                  <span>Enviar solicitud</span>
                </button>
              </form>
            )}

            <div className="flex flex-col sm:flex-row items-center justify-center gap-6 pt-6 border-t border-accent/20 w-full text-foreground/80 text-sm">
              <a href="mailto:hola@renexa.es" className="flex items-center gap-2 hover:text-primary-cta transition-colors">
                <Mail className="w-4 h-4 text-primary-cta" />
                <span>hola@renexa.es</span>
              </a>
              <a href="tel:+34604250250" className="flex items-center gap-2 hover:text-primary-cta transition-colors">
                <Phone className="w-4 h-4 text-primary-cta" />
                <span>604 250 250</span>
              </a>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
