// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Preguntas"
          title="Dudas frecuentes"
          description="Todo lo que necesitas saber antes de empezar tu transformación."
          items={[
            {
              question: "¿Es muy difícil integrar la IA?",
              answer: "Diseñamos sistemas que se integran de forma fluida con tus herramientas actuales sin disrupción.",
            },
            {
              question: "¿Qué tipo de soporte ofrecen?",
              answer: "Brindamos soporte técnico continuo y entrenamiento para tu equipo durante todo el proceso.",
            },
            {
              question: "¿Cómo se mide el éxito?",
              answer: "Definimos KPIs claros desde el inicio para asegurar un ROI positivo y medible.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
