// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesMediaCarousel from '@/components/sections/features/FeaturesMediaCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesMediaCarousel
          tag="Soluciones"
          title="IA e Integración al Servicio de tu Crecimiento"
          description="Nuestros servicios escalables ayudan a empresas de todos los tamaños a operar con mayor inteligencia y eficiencia."
          items={[
            {
              title: "Automatización de Tareas",
              description: "Reduce costos operativos eliminando procesos manuales tediosos con IA.",
              buttonIcon: "Zap",
              imageSrc: "http://img.b2bpic.net/free-photo/team-technicians-data-center-using-laptop-visualize-ai_482257-106308.jpg",
            },
            {
              title: "Pronóstico de Ventas",
              description: "Predice tendencias de ingresos y optimiza inventarios con algoritmos precisos.",
              buttonIcon: "TrendingUp",
              imageSrc: "http://img.b2bpic.net/free-photo/young-general-manager-using-green-screen-evaluating-performance-metrics_482257-124506.jpg",
            },
            {
              title: "Asistentes IA Inteligentes",
              description: "Atención al cliente 24/7 y gestión de leads con chatbots de lenguaje natural.",
              buttonIcon: "MessageSquare",
              imageSrc: "http://img.b2bpic.net/free-photo/flowchart-information-methodology-operation-icon_53876-133778.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
