// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
          tag="Renexa Innovación"
          title="Transforma tu empresa con IA e integración digital"
          description="Automatiza procesos complejos, predice ventas y escala sin límites. Desde diseño web hasta chatbots inteligentes, te llevamos a la transformación digital que necesitas."
          primaryButton={{
            text: "Solicitar demostración",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Ver casos de éxito",
            href: "#features",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-accounting-sales-statistics-computer-display_482257-122982.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/server-room-worker-oversees-ai-systems-processing-information_482257-110575.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/positive-worker-dancing-having-fun-startup-office-enjoying-listening-music-work-break-african-american-executive-manager-doing-dance-moves-after-finishing-company-investment-strategy_482257-74335.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/futurism-perspective-digital-nomads-lifestyle_23-2151252523.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-it-professional-using-tablet-building-ai-algorithms_482257-100475.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/hands-multitasking-with-laptop-notebook_23-2149311907.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
