// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="ROI Comprobado"
          title="Impacto Medible para tu Negocio"
          description="Datos que demuestran la eficacia de nuestras implementaciones de IA."
          metrics={[
            {
              value: "40%",
              description: "Reducción en costos operativos",
            },
            {
              value: "3x",
              description: "Incremento en tasa de conversión",
            },
            {
              value: "24/7",
              description: "Disponibilidad de atención al cliente",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
