// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialOverlayCards from '@/components/sections/testimonial/TestimonialOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialOverlayCards
          tag="Clientes"
          title="Lo que dicen nuestros líderes"
          description="Historias de éxito de empresas que transformaron su operación con Renexa."
          testimonials={[
            {
              name: "Sarah Johnson",
              role: "CEO",
              company: "RetailGrowth",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/young-businessman-happy-expression_1194-1674.jpg",
            },
            {
              name: "Michael Chen",
              role: "CTO",
              company: "InnovateLog",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/happy-male-entrepreneur-using-desktop-pc-while-working-office-there-are-people-background_637285-1037.jpg",
            },
            {
              name: "Emily Rodriguez",
              role: "Ops Manager",
              company: "ServiceFlow",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/business-man-working-late-office_23-2148991380.jpg",
            },
            {
              name: "David Kim",
              role: "Director",
              company: "EcommercePro",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/charming-girl-with-laptop-office_23-2147787594.jpg",
            },
            {
              name: "Ana Sofia",
              role: "Strategy Lead",
              company: "MarketDynamics",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/general-manager-leverages-analytics-report-writing-corporate-development-forecast_482257-136465.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
